server:
  servlet:
    context-path:  /yr-app-server
  port: 8082
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: @profileActive@

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.yr.net.app.base.entity,com.yr.net.app.common.entity,com.yr.net.app.customer.entity,com.yr.net.app.log.entity,com.yr.net.app.message.entity,com.yr.net.app.moments.entity,com.yr.net.app.monitor.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
